# ??? ?? ?? ??? ??? ???? ?? ??
spring:
  output:
    ansi:
      enabled: always

# 8080, 8081, 8082 ? ??? ?? ??? ????? 3?? ???? ?? ?????.
server:
  port: 8080

zookeeper:
  connectionString: your.zookeeper.ip.address:2181